name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: build-release
    steps:
    - uses: actions/checkout@v2
    - name: Build runner
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}/runner
        registry: docker.pkg.github.com
        target: runner
        tags: latest
    - name: Build SAFE runner
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}/safe
        registry: docker.pkg.github.com
        tags: latest
